#!/usr/bin/with-contenv bash

echo "[cont-init.d] Setting up ICEcoder environment"
chsh abc -s /bin/bash
echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel
adduser abc wheel

if [[ -n ${GITURL} ]] && [[ ! -f /code/giturl.lock ]]; then
  echo "Cloning ${GITURL} into /code"
  mkdir -p /code && cd /code && git clone "$GITURL"
  chown -R abc:abc \
    /code
  chmod -R 775 \
    /code
  touch /code/giturl.lock
elif [[ -z ${GITURL} ]] && [[ ! -f /code/giturl.lock ]]; then
  chown -R abc:abc \
    /code
  chmod -R 775 \
    /code
  touch /giturl.lock
else
  echo "Either GITURL was not specified or was already cloned"
fi

# make our folders
mkdir -p \
  /config/{log/ICEcoder,php,sess}

# create lock file after first run
touch /lock.file

# copy php ini for user editing
[[ ! -e "/config/php/php.ini" ]] && \
  cp /etc/php7/php.ini /config/php/php.ini
cp /config/php/php.ini /etc/php7/php.ini

# Link data, code and plugins
ln -sf /data /app/ICEcoder/data
ln -sf /plugins /app/ICEcoder/plugins
ln -sf /code /app/ICEcoder/code

# permissions
mkdir -p /config/sessions
echo "[cont-init.d] Setting permissions. This may take some time"

chown -R \
  abc:abc \
    /app/ICEcoder \
    /data \
    /config \
    /plugins

chmod -R \
  775 \
    /app/ICEcoder \
    /data \
    /config \
    /plugins
